 DROP TABLE IF EXISTS PESSOA;

CREATE TABLE PESSOA (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(200),
  idade INTEGER
);


INSERT INTO PESSOA (nome,idade) VALUES
  ('Rogerio',24);

INSERT INTO PESSOA (nome,idade) VALUES
('Carlos',30);